language: java
jdk:
- openjdk11
branches:
  only:
  - master
before_install:
  # 복호화 후 다시 원위치로 옮김
- openssl aes-256-cbc -K $encrypted_1116e8e6e492_key -iv $encrypted_1116e8e6e492_iv
  -in application.yml.enc -out src/main/resources/application.yml -d
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"

# deploy 실행 전 수행
# CodeDeploy는 jar파일 인식 못하므로 zip파일로 압축한 뒤 전달
before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/unigram-webservice.zip # deploy로 zip파일 이동

# 외부 서비스와 연동될 명령어 정의
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis settings
    secret_access_key: $AWS_SECRET_KEY

    bucket: unigram # 버킷 이름
    region: ap-northeast-2 # AWS 리전
    skip_cleanup: true
    acl: private
    local_dir: deploy     # deploy 위치의 파일만 s3로 전송
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: unigram
    key: unigram-webservice.zip
    bundle_type: zip
    application: unigram-webservice
    deployment_group: unigram-deploy-group
    region: ap-northeast-2
    wait_until_deployed: true

notifications:
  slack:
    rooms:
      secure: afMiBuzQ/hjO6QQExmX81Ykscuoi4z2Afd3nGEqhdav/llgztPMPKIHPtUmzCgc6PtD1f3jFRMmxlUDCJAlz+4CVJLCGjSWTvKDEXRQLDuuhpSXlquwbVcOMAlA/Xluqyr4jlz/r1JZHdvJFljR/Umimptn+M9/K9jJTzGYvIGtrM3242scPEZbO/Hpotcm2fqnQGW8RMpFCRsn6Tr+Qji4vY6LVFbWzxrxkOkIb2TLCU4zxJ6R3westxjpO+AxYtAM1A2QfatUHzZ2MHUgWhqCIPxIRTjnoyVfollP+E3rG8roT1iWaq7IdmHCJ/vvioU2ith2hSgHQvoYCYo/6whmwIrchdCzqFGv/+QaEeXyCRwV5w9A+nNhA0W1bq0o1dRqq7IAWhuDdbrPxAyx0aAxgaebwxYXPY32e4zI0m0NjI6OS6SSYOrub1wGCHTF1JfCIe8uy3U4c7GMYtNXiKN8BylXDqbMOn/MAKZ482FuOE/nb2jog3E0+Wih7V+0eKW8z5Y4FZyiKwxqINqv4XTh3+HD/HPEYlk6gMYkkwHvncNSL3Ox2HE7/d81GIQgexwE6Sqgd689SKQ99S1gzw3vYdHcK1bV+FbHa3a+E1pa4HiX3MNFZseym/6i/ucW4xOSYD/EdEKRHzU10EQTTe2GFcfhFqLqswaO7rflkdTQ=
